### ISSUE TITLE
List more than 50 videos

### ISSUE THREAD

**Issue by Henqsan** [Lipdroid/YoutubeAPIV3#1]
Hello, great app!

Using your example is it possible to list more than 50 videos from a playlist?
If yes, how?

Another question, is it possible to format the return of the date, for example 18-08-2018 H 22:55:35?

**Comment by rudreshmehta** [comment]
> Hello, great app!
> 
> Using your example is it possible to list more than 50 videos from a playlist?
> If yes, how?
> 
> Another question, is it possible to format the return of the date, for example 18-08-2018 H 22:55:35?

that can be done using some logic , dont need to panic in code for this . inbuilt DateFormat class will help you in android while doing with it java.

**Comment by Lipdroid** [comment]
i think you got your answer
